### ISSUE TITLE
bbq! macro should be unsafe

### ISSUE THREAD

**Issue by japaric** [jamesmunns/bbqueue#16]
The documentation says:

> this macro is not intrinsically thread safe!

So the macro should be unsafe to call. Also, since this macro is unchecked you may as well directly return `&'static mut BBQueue` (without the `Option`).

I would also recommend adding a safe, checked variant that enforces singleton-ness using atomics -- see second snippet in https://github.com/rust-embedded/cortex-m/issues/128#issuecomment-452630307 .

**Comment by jamesmunns** [comment]
Sounds good! I'll likely add your suggestion to `bbq!()`, and move the current impl to `unsafe bbq_unchecked!()` or similar.
