### ISSUE TITLE
panic upon committing a zero-sized grant

### ISSUE THREAD

**Issue by Disasm** [jamesmunns/bbqueue#30]
Sometimes zero-sized grant points beyond the buffer size (grant_ptr=buffer_ptr+buffer_len), with such grant `commit` panics on `assert!(self.is_our_grant(&grant.buf));`.

**Comment by jonas-schievink** [comment]
Repro:

```rust
use bbqueue::*;

fn main() {
    let bbq = bbq!(1000).unwrap();

    let size = 1000;
    let grant = bbq.grant(size).unwrap();
    bbq.commit(size, grant);

    let grant = bbq.grant(0).unwrap();
    bbq.commit(0, grant);
}
```

**Comment by jamesmunns** [comment]
I'd be open for a PR that fixes the check in `is_our_grant`!
