### ISSUE TITLE
BBQueue backing storage is put in `.data` instead of `.bss`

### ISSUE THREAD

**Issue by jonas-schievink** [jamesmunns/bbqueue#43]
See https://github.com/jonas-schievink/rubble/pull/100

This is a regression from 0.3.0 to 0.4.0.

**Comment by jonas-schievink** [comment]
Hmm, https://github.com/rust-embedded/cortex-m-rt/issues/116 claims that `MaybeUninit` data will end up in `.bss`, but there was also https://github.com/rtfm-rs/cortex-m-rtfm/issues/52 and https://github.com/rust-lang/rust/issues/41315, which has apparently now been fixed, but maybe there is another rustc bug behind this?

**Comment by jamesmunns** [comment]
For reference, here is where I am explicitly zeroing the backing structure, and likely the source of why this is showing up in .data:

https://docs.rs/bbqueue/0.4.0/src/bbqueue/atomic.rs.html#127-128

**Comment by jamesmunns** [comment]
It's a little disappointing that the compiler isn't picking up that this is just zeroed in static (as bss) (or the optimizer decided that a memcpy is better than a memset)

**Comment by jamesmunns** [comment]
Also also for reference, I did try manually swapping the `write_bytes` call to a loop with a loop + `ptr::write`, and the generated code seemed the same, though I might need something more like https://github.com/japaric/r0/blob/master/src/lib.rs#L167-L176 to deter the optimizer, at the cost of a slower initialization.
