### ISSUE TITLE
Reduce size of Grants for Framed operation

### ISSUE THREAD

**Issue by jamesmunns** [jamesmunns/bbqueue#47]
Right now, the `hdr_len` field of `FrameGrantW` and `FrameGrantR` is of type `usize`, though the only possible values are `0..=9`, as these are the only possible lengths of the header.

It would be good to change the type from `usize` to `u8`, and handle this appropriately in all handling code. This should be as easy as changing the types, and fixing any compilation errors. We should add debug asserts as well to ensure there have not been any logic errors.

**Comment by yazdan** [comment]
Hi I'd be happy to help

**Comment by jamesmunns** [comment]
Closed by #53!
